CP2-PETS/Models/ErrorViewModel.cs
namespace CP2_PETS.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

CP2-PETS/Models/Pet.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace CP2_PETS.Models;

public class Pet
{
    [HiddenInput]
    public int Id { get; set; }
    
    public string Nome {get; set;}
    
    public TipoPet Tipo {get; set;}
    
    [Display(Name = "Raça")]
    public string? Raca {get; set;}
    
    [Display(Name = "Data de Nascimento")]
    public DateTime DataNascimento {get; set;}
    
    public SexoPet Sexo {get; set;}
    
    public double? Peso {get; set;}
    
    [Display(Name = "Nome Completo do Dono")]
    public string NomeDono {get; set;}
    
    [Display(Name = "Telefone do Dono")]
    public string ContatoDono { get; set; }
    
    [Display(Name = "É vacinado?")]
    public bool Vacinado {get; set;}

    public enum TipoPet
    {
        Cachorro,
        Gato,
        [Display(Name = "Pássaro")]
        Passaro,
        Peixe,
        Coelho,
        Hamster,
        [Display(Name = "Réptil")]
        Reptil,
        [Display(Name = "Porquinho Da Índia")]
        PorquinhoDaIndia,
        Cavalo,
        Outros
    }

    public enum SexoPet
    {
        Macho,
        [Display(Name = "Fêmea")]
        Femea
    }
}

CP2-PETS/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CP2_PETS.Models;

namespace CP2_PETS.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CP2-PETS/Controllers/PetController.cs
using CP2_PETS.Models;
using Microsoft.AspNetCore.Mvc;

namespace CP2_PETS.Controllers;

public class PetController : Controller
{
    private static List<Pet> _lista = new List<Pet>();
    private static int _id = 0;

    [HttpPost]
    public IActionResult Remover(int id)
    {
        _lista.RemoveAt(_lista.FindIndex(p => p.Id == id));
        TempData["msg"] = "Pet removido com sucesso!";
        return RedirectToAction("Index");
    }
    
    [HttpPost]
    public IActionResult Editar(Pet pet)
    {
        var index = _lista.FindIndex(p => p.Id == _id);
        _lista[index] = pet;
        TempData["msg"] = "Pet atualizado com sucesso!";
        return RedirectToAction("Editar");
    }
    
    [HttpGet]
    public IActionResult Editar(int id)
    {
        var index = _lista.FindIndex(p => p.Id == id);
        var pet = _lista[index];
        return View(pet);
    }
    
    public IActionResult Index()
    {
        return View(_lista);
    }

    // VISUALIZAR A LISTA DE PETS
    [HttpGet]
    public IActionResult Cadastrar()
    {
        return View();
    }

    // CADASTRO DO PET
    [HttpPost]
    public IActionResult Cadastrar(Pet pet)
    {
        pet.Id = ++_id;
        _lista.Add(pet);
        TempData["msg"] = "Pet cadastrado!";
        return RedirectToAction("Cadastrar");
    }
}

CP2-PETS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">FIAP Pets</h1>
    <a asp-controller="pet" asp-action="cadastrar" >Cadastro de Pet</a>
</div>

CP2-PETS/Views/Pet/Cadastrar.cshtml
@model Pet

@{
    ViewData["Title"] = "Cadastro de Pet";
}

<h1>Cadastro de Pet</h1>

<mensagem texto="@TempData["msg"]"></mensagem>

<form asp-action="Cadastrar">
    <partial name="_Form"/>
    <botao></botao>
    <a asp-action="Index" class="btn btn-dark">Lista de Pets</a>
</form>

CP2-PETS/Views/Pet/Editar.cshtml
@model Pet

@{
    ViewData["Title"] = "Editar Pet";
}

<h1>Editar Pet</h1>

<mensagem texto="@TempData["msg"]"></mensagem>

<form asp-action="Editar">
    <partial name="_Form"/>
    <botao texto="Editar"></botao>
    <a asp-action="Index" class="btn btn-dark">Lista de Pets</a>
</form>

CP2-PETS/Views/Pet/Index.cshtml
@model List<Pet>

@{
    ViewData["Title"] = "Pets";
}

@section Banner {
    <div class="alert alert-info text-center">
        Quer adotar um pet? Clique aqui!
    </div>
}

<h1>Pets</h1>

<mensagem texto="@TempData["msg"]" class="alert alert-danger"></mensagem>

<a asp-action="Cadastrar" class="btn btn-sm btn-outline-danger">Cadastrar</a>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Tipo</th>
        <th>Raça</th>
        <th>Data de Nascimento</th>
        <th>Sexo</th>
        <th>Peso</th>
        <th>Vacinado</th>
        <th>Nome do Dono</th>
        <th>Contato do Dono</th>
        <th></th>
    </tr>
    @foreach (var p in Model)
    {
        <tr>
            <td>@p.Nome</td>
            <td>@p.Tipo</td>
            <td>@p.Raca</td>
            <td>@p.DataNascimento</td>
            <td>@p.Sexo</td>
            <td>@(p.Vacinado?"Sim":"Não")</td>
            <td>@p.NomeDono</td>
            <td>@p.ContatoDono</td>
            <td>
                <a asp-action="Editar" class="btn btn-sm btn-outline-primary" asp-route-id="@p.Id">
                    Editar
                </a>
                <button onclick="petId.value = @p.Id" type="button" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Remover
                </button>
            </td>
        </tr>
    }
</table>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmação</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Deseja realmente remover o pet?
            </div>
            <div class="modal-footer">
                <form asp-action="remover">
                    <input name="id" type="hidden" id="petId"/>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
                    <button type="submit" class="btn btn-danger">Sim</button>
                </form>
            </div>
        </div>
    </div>
</div>

CP2-PETS/Views/Pet/_Form.cshtml
@model Pet

<input asp-for="Id"/>
<div class="mb-3">
    <label asp-for="Nome"></label>
    <input asp-for="Nome" class="form-control" />
</div>
<div class="mb-3">
    <label asp-for="Tipo"></label>
    <select asp-for="Tipo" class="form-select"
            asp-items="@Html.GetEnumSelectList<Pet.TipoPet>()">
        <option>Selecione</option>
    </select>
</div>
<div class="mb-3">
    <label asp-for="Raca"></label>
    <input asp-for="Raca" class="form-control" />
</div>
<div class="mb-3">
    <label asp-for="DataNascimento"></label>
    <input asp-for="DataNascimento" class="form-control" />
</div>
<div class="mb-3">
    <label asp-for="Sexo"></label>
    <select asp-for="Sexo" class="form-select"
            asp-items="@Html.GetEnumSelectList<Pet.SexoPet>()">
        <option>Selecione</option>
    </select>
</div>
<div class="mb-3">
    <label asp-for="Peso"></label>
    <input asp-for="Peso" class="form-control" />
</div>
<div class="mb-3">
    <label asp-for="NomeDono"></label>
    <input asp-for="NomeDono" class="form-control" />
</div>
<div class="mb-3">
    <label asp-for="ContatoDono"></label>
    <input asp-for="ContatoDono" class="form-control" />
</div>
<div class="mb-3">
    <label asp-for="Vacinado"></label>
    <input asp-for="Vacinado"/>
</div>

CP2-PETS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FIAP Pets</title>
    <link rel="stylesheet" href="https://bootswatch.com/5/slate/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/CP2_PETS.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FIAP Pets</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Pet
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-action="Cadastrar" asp-controller="Pet">Cadastrar</a></li>
                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Pet">Listar</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

    <footer class="border-top footer text-muted">
        <div>
            @RenderSection("Banner", false)
        </div>
        <div class="container">
            &copy; 2025 - FIAP Pets - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>